//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResmarkPrinterGroupDemo.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResmarkPrinterGroupDemo.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        internal static string AddPrinter {
            get {
                return ResourceManager.GetString("AddPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Available messages ähnelt.
        /// </summary>
        internal static string AvailableMessages {
            get {
                return ResourceManager.GetString("AvailableMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string ConfigCancelButton {
            get {
                return ResourceManager.GetString("ConfigCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning: Invalid entries in this configuration may cause system malfunction. Do you really want to continue? ähnelt.
        /// </summary>
        internal static string ConfigDangerPrompt {
            get {
                return ResourceManager.GetString("ConfigDangerPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to load configuration. ähnelt.
        /// </summary>
        internal static string ConfigLoadError {
            get {
                return ResourceManager.GetString("ConfigLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string ConfigSaveButton {
            get {
                return ResourceManager.GetString("ConfigSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configuration saved. ähnelt.
        /// </summary>
        internal static string ConfigSaved {
            get {
                return ResourceManager.GetString("ConfigSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to save configuration. ähnelt.
        /// </summary>
        internal static string ConfigSaveError {
            get {
                return ResourceManager.GetString("ConfigSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Print Head Configuration ähnelt.
        /// </summary>
        internal static string ConfigTitle {
            get {
                return ResourceManager.GetString("ConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to delete the file &quot;{0}&quot;? ähnelt.
        /// </summary>
        internal static string ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connection failed ähnelt.
        /// </summary>
        internal static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not delete the file: {0} ähnelt.
        /// </summary>
        internal static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file was successfully deleted. ähnelt.
        /// </summary>
        internal static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Message ähnelt.
        /// </summary>
        internal static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Done ähnelt.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Variables (Group) ähnelt.
        /// </summary>
        internal static string EditGroupVariables {
            get {
                return ResourceManager.GetString("EditGroupVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Variables ähnelt.
        /// </summary>
        internal static string EditVariables {
            get {
                return ResourceManager.GetString("EditVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The message is empty or could not be recalled. ähnelt.
        /// </summary>
        internal static string ErrorEmptyRecall {
            get {
                return ResourceManager.GetString("ErrorEmptyRecall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to load preview image. ähnelt.
        /// </summary>
        internal static string ErrorPreview {
            get {
                return ResourceManager.GetString("ErrorPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to recall or save message: ähnelt.
        /// </summary>
        internal static string ErrorRecall {
            get {
                return ResourceManager.GetString("ErrorRecall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file does not exist. ähnelt.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please fill in all fields. ähnelt.
        /// </summary>
        internal static string FillAllFields {
            get {
                return ResourceManager.GetString("FillAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} printers found. ähnelt.
        /// </summary>
        internal static string FoundPrinters {
            get {
                return ResourceManager.GetString("FoundPrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Printer groups ähnelt.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group Variables ähnelt.
        /// </summary>
        internal static string GroupVariablesTitle {
            get {
                return ResourceManager.GetString("GroupVariablesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IP Address ähnelt.
        /// </summary>
        internal static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message File (XML) ähnelt.
        /// </summary>
        internal static string MessageFile {
            get {
                return ResourceManager.GetString("MessageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message saved: ähnelt.
        /// </summary>
        internal static string MessageSaved {
            get {
                return ResourceManager.GetString("MessageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No new printers found ähnelt.
        /// </summary>
        internal static string NoPrintersFound {
            get {
                return ResourceManager.GetString("NoPrintersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add / Update ähnelt.
        /// </summary>
        internal static string OffsetAddOrUpdate {
            get {
                return ResourceManager.GetString("OffsetAddOrUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string OffsetButtonCancel {
            get {
                return ResourceManager.GetString("OffsetButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        internal static string OffsetButtonRemove {
            get {
                return ResourceManager.GetString("OffsetButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string OffsetButtonSave {
            get {
                return ResourceManager.GetString("OffsetButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Offsets ähnelt.
        /// </summary>
        internal static string OffsetFormTitle {
            get {
                return ResourceManager.GetString("OffsetFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        internal static string OffsetRemove {
            get {
                return ResourceManager.GetString("OffsetRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offset removed. ähnelt.
        /// </summary>
        internal static string OffsetRemoved {
            get {
                return ResourceManager.GetString("OffsetRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Offset ähnelt.
        /// </summary>
        internal static string OffsetRemoveTitle {
            get {
                return ResourceManager.GetString("OffsetRemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to remove the selected offset? ähnelt.
        /// </summary>
        internal static string OffsetRemoveWarning {
            get {
                return ResourceManager.GetString("OffsetRemoveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offsets saved successfully. ähnelt.
        /// </summary>
        internal static string OffsetSaved {
            get {
                return ResourceManager.GetString("OffsetSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offsets have been saved. ähnelt.
        /// </summary>
        internal static string OffsetsSaved {
            get {
                return ResourceManager.GetString("OffsetsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offset Value ähnelt.
        /// </summary>
        internal static string OffsetValue {
            get {
                return ResourceManager.GetString("OffsetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pause ähnelt.
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message Preview ähnelt.
        /// </summary>
        internal static string PreviewTitle {
            get {
                return ResourceManager.GetString("PreviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Print ähnelt.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Print Count ähnelt.
        /// </summary>
        internal static string PrintCount {
            get {
                return ResourceManager.GetString("PrintCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Printer ID ähnelt.
        /// </summary>
        internal static string PrinterId {
            get {
                return ResourceManager.GetString("PrinterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Printer IP ähnelt.
        /// </summary>
        internal static string PrinterIP {
            get {
                return ResourceManager.GetString("PrinterIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Printers ähnelt.
        /// </summary>
        internal static string Printers {
            get {
                return ResourceManager.GetString("Printers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message was sent to printer successfully. ähnelt.
        /// </summary>
        internal static string PrintSuccess {
            get {
                return ResourceManager.GetString("PrintSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        internal static string RemovePrinter {
            get {
                return ResourceManager.GetString("RemovePrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resume ähnelt.
        /// </summary>
        internal static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan Printers ähnelt.
        /// </summary>
        internal static string ScanPrinters {
            get {
                return ResourceManager.GetString("ScanPrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Searching network... ähnelt.
        /// </summary>
        internal static string SearchStatus {
            get {
                return ResourceManager.GetString("SearchStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select a message first. ähnelt.
        /// </summary>
        internal static string SelectMessage {
            get {
                return ResourceManager.GetString("SelectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Message ähnelt.
        /// </summary>
        internal static string SelectMsg {
            get {
                return ResourceManager.GetString("SelectMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send to All ähnelt.
        /// </summary>
        internal static string SendToAll {
            get {
                return ResourceManager.GetString("SendToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Variable editor opened. ähnelt.
        /// </summary>
        internal static string StatusEditVariables {
            get {
                return ResourceManager.GetString("StatusEditVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Printing paused. ähnelt.
        /// </summary>
        internal static string StatusPause {
            get {
                return ResourceManager.GetString("StatusPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Printer added. ähnelt.
        /// </summary>
        internal static string StatusPrinterAdded {
            get {
                return ResourceManager.GetString("StatusPrinterAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Printer removed. ähnelt.
        /// </summary>
        internal static string StatusPrinterRemoved {
            get {
                return ResourceManager.GetString("StatusPrinterRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status: ready ähnelt.
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status refreshed ähnelt.
        /// </summary>
        internal static string StatusRefreshed {
            get {
                return ResourceManager.GetString("StatusRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Printing resumed. ähnelt.
        /// </summary>
        internal static string StatusResume {
            get {
                return ResourceManager.GetString("StatusResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stored message sent. ähnelt.
        /// </summary>
        internal static string StatusSelectMessage {
            get {
                return ResourceManager.GetString("StatusSelectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sending message to all printers… ähnelt.
        /// </summary>
        internal static string StatusSending {
            get {
                return ResourceManager.GetString("StatusSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sending message to all printers… ähnelt.
        /// </summary>
        internal static string StatusSendMessage {
            get {
                return ResourceManager.GetString("StatusSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message has been sent. ähnelt.
        /// </summary>
        internal static string StatusSent {
            get {
                return ResourceManager.GetString("StatusSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Printing stopped. ähnelt.
        /// </summary>
        internal static string StatusStop {
            get {
                return ResourceManager.GetString("StatusStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop ähnelt.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To XML ähnelt.
        /// </summary>
        internal static string ToXML {
            get {
                return ResourceManager.GetString("ToXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string VariableName {
            get {
                return ResourceManager.GetString("VariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Variables have been saved. ähnelt.
        /// </summary>
        internal static string VariablesSaved {
            get {
                return ResourceManager.GetString("VariablesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Variables – {0} ähnelt.
        /// </summary>
        internal static string VariablesTitle {
            get {
                return ResourceManager.GetString("VariablesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value ähnelt.
        /// </summary>
        internal static string VariableValue {
            get {
                return ResourceManager.GetString("VariableValue", resourceCulture);
            }
        }
    }
}
